### ISSUE TITLE
Cannot read property 'securitySchemes' of undefined

### ISSUE THREAD

**Issue by prichey** [ErikWittern/openapi-snippet#46]
Getting this with a valid Swagger file:

```
TypeError: Cannot read property 'securitySchemes' of undefined
    at getHeadersArray (/repo/node_modules/openapi-snippet/openapi-to-har.js:309:48)
    at createHar (/repo/node_modules/openapi-snippet/openapi-to-har.js:44:14)
    at Object.openApiToHarList [as getAll] (/repo/node_modules/openapi-snippet/openapi-to-har.js:379:21)
    at Object.getSnippets (/repo/node_modules/openapi-snippet/index.js:63:32)
```

Looks like `openapi-to-har.js` expects `openApi.components.securitySchemes` to exist even though it's not required for OAS v2.

**Comment by sa-mustafa** [comment]
Same feeling here. However, after a bit of debugging '_openapi-to-har.js_', I found out that some of my endpoint definitions lacked '_security:_' tag. For more info, see the swagger [api keys](https://swagger.io/docs/specification/2-0/authentication/api-keys/).
You can also upgrade your doc from Swagger (i.e. OAS v1/2) to OpenAPI v3.

**Comment by ran-huang** [comment]
Getting the same error. I have a global `security` section on the root level so I'm not sure why the error occurs. The error is related to [this line](https://github.com/ErikWittern/openapi-snippet/blob/2e6c2c91859c56442f134ced22ef609e7b4b36cd/openapi-to-har.js#L442)

**Comment by BartoszPluta** [comment]
For the future of the solution proposal just add in your schema

> openapi: '3.0.0',
